[package]
name = "system"
version.workspace = true
publish.workspace = true
license.workspace = true
categories.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
nix = { workspace = true }
[lints]
workspace = true
