[package]
name = "easyinit-user"
description = "Handles the user scope of easyinit"
version.workspace = true
publish.workspace = true
license.workspace = true
categories.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]

[lints]
workspace = true
