[package]
name = "easyinitlib"
description = "The bridge between easyinit and easyctl"
version.workspace = true
publish.workspace = true
license.workspace = true
categories.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]

[lints]
workspace = true
